# Generated by Django 5.1.6 on 2025-10-17 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_no", models.CharField(max_length=50)),
                ("flight_no", models.CharField(max_length=50)),
                ("crew_role", models.CharField(max_length=50)),
                ("crew_name", models.CharField(max_length=120)),
                ("personal_no", models.CharField(max_length=50)),
                ("cat_state", models.CharField(max_length=50)),
                ("current_datetime", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Crew Detail",
                "verbose_name_plural": "Crew Details",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TWCCConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("version", models.CharField(default="v1", max_length=32)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "TWCC Configuration",
                "verbose_name_plural": "TWCC Configurations",
                "ordering": ["-updated_at"],
            },
        ),
    ]
