# Generated by Django 5.1.6 on 2025-10-17 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_crewdetail_twccconfiguration"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="db_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="db_port",
            field=models.PositiveIntegerField(default=5432),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="db_transport",
            field=models.CharField(default="postgres", max_length=16),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="if_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="if_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="if_transport",
            field=models.CharField(default="http", max_length=16),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_internal_comm_port",
            field=models.PositiveIntegerField(default=6006),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_nrt_port",
            field=models.PositiveIntegerField(default=6005),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_track_port",
            field=models.PositiveIntegerField(default=54674),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="ows_transport",
            field=models.CharField(default="http", max_length=16),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="record_interval",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="recording_flag",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="wa_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="wa_port",
            field=models.PositiveIntegerField(default=80),
        ),
        migrations.AddField(
            model_name="twccconfiguration",
            name="wa_transport",
            field=models.CharField(default="http", max_length=16),
        ),
    ]
