# Generated by Django 5.1.6 on 2025-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_user_options_twccconfiguration_db_ip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twccconfiguration",
            name="db_ip",
            field=models.CharField(
                default="127.0.0.1",
                help_text="Database host/IP (localhost for single PC).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="if_ip",
            field=models.CharField(
                default="127.0.0.1",
                help_text="IF host/IP (localhost for single PC).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Mark the currently effective config."
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="ows_ip",
            field=models.CharField(
                default="127.0.0.1",
                help_text="OWS host/IP (localhost for single PC).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="payload",
            field=models.JSONField(
                blank=True, default=dict, help_text="Free-form config payload."
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="record_interval",
            field=models.PositiveIntegerField(
                default=1, help_text="Interval units per app semantics (e.g., seconds)."
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="wa_ip",
            field=models.CharField(
                default="127.0.0.1",
                help_text="WA host/IP (localhost for single PC).",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="wa_port",
            field=models.PositiveIntegerField(default=6002),
        ),
    ]
