# Generated by Django 5.1.6 on 2025-10-17 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_twccconfiguration_db_ip_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="twccconfiguration",
            name="if_port",
            field=models.PositiveIntegerField(default=6007),
        ),
    ]
