# Generated by Django 5.1.6 on 2025-10-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_twccconfiguration_if_port"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="db_port",
        ),
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="db_transport",
        ),
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="if_transport",
        ),
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="ows_port",
        ),
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="ows_transport",
        ),
        migrations.RemoveField(
            model_name="twccconfiguration",
            name="wa_transport",
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="db_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="if_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="if_port",
            field=models.IntegerField(default=6007),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="ows_internal_comm_port",
            field=models.IntegerField(default=6006),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="ows_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="ows_nrt_port",
            field=models.IntegerField(default=6005),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="ows_track_port",
            field=models.IntegerField(default=54674),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="payload",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="record_interval",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="wa_ip",
            field=models.CharField(default="127.0.0.1", max_length=255),
        ),
        migrations.AlterField(
            model_name="twccconfiguration",
            name="wa_port",
            field=models.IntegerField(default=6002),
        ),
    ]
