# Generated by Django 5.1.6 on 2025-10-17 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_twccconfiguration_db_port_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CrewDetailsLegacy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unitno", models.IntegerField()),
                ("flightno", models.CharField(max_length=100)),
                ("crewrole", models.CharField(max_length=100)),
                ("crewname", models.CharField(max_length=100)),
                ("personalno", models.CharField(max_length=100)),
                ("catstate", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
            ],
            options={
                "db_table": "core_crewdetails_legacy",
                "ordering": ["-datetime", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CrewRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.IntegerField(unique=True)),
                ("role_name", models.CharField(max_length=255, unique=True)),
            ],
            options={
                "ordering": ["role_name"],
            },
        ),
        migrations.AlterModelOptions(
            name="crewdetail",
            options={
                "ordering": ["-current_datetime", "-id"],
                "verbose_name": "Crew Detail",
                "verbose_name_plural": "Crew Details",
            },
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="cat_state",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="crew_name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="crew_role",
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="flight_no",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="personal_no",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="crewdetail",
            name="unit_no",
            field=models.CharField(db_index=True, max_length=32),
        ),
        migrations.AddIndex(
            model_name="crewdetail",
            index=models.Index(
                fields=["unit_no", "flight_no"], name="core_crewde_unit_no_e7a076_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewdetail",
            index=models.Index(
                fields=["personal_no"], name="core_crewde_persona_046368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewdetail",
            index=models.Index(
                fields=["current_datetime"], name="core_crewde_current_5071e8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewdetailslegacy",
            index=models.Index(
                fields=["unitno", "flightno"], name="core_crewde_unitno_8d9b01_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewdetailslegacy",
            index=models.Index(
                fields=["personalno"], name="core_crewde_persona_c081b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="crewdetailslegacy",
            index=models.Index(
                fields=["datetime"], name="core_crewde_datetim_ee781a_idx"
            ),
        ),
    ]
