# Generated by Django 5.1.6 on 2025-10-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_add_crewrole_and_legacy"),
    ]

    operations = [
        migrations.AlterField(
            model_name="crewdetail",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="crewdetailslegacy",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
