# Generated by Django 5.1.6 on 2025-10-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_add_siteconfig"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlightInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unitno", models.IntegerField(db_index=True)),
                ("flightno", models.CharField(db_index=True, max_length=255)),
                ("type_of_sagw_weapon", models.IntegerField()),
            ],
            options={
                "ordering": ["unitno", "flightno"],
                "indexes": [
                    models.Index(
                        fields=["unitno", "flightno"],
                        name="core_flight_unitno_457ad2_idx",
                    )
                ],
            },
        ),
    ]
