# Generated by Django 5.1.6 on 2025-09-30 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DefendedAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("radius_km", models.FloatField(default=20.0)),
            ],
        ),
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("track_id", models.CharField(db_index=True, max_length=64)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("alt_m", models.FloatField()),
                ("speed_mps", models.FloatField()),
                ("heading_deg", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ThreatScore",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cpa_km", models.FloatField(blank=True, null=True)),
                ("tcpa_s", models.FloatField(blank=True, null=True)),
                ("tdb_km", models.FloatField(blank=True, null=True)),
                ("twrp_s", models.FloatField(blank=True, null=True)),
                ("score", models.FloatField(blank=True, null=True)),
                ("computed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "da",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tewa.defendedasset",
                    ),
                ),
                (
                    "track",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tewa.track"
                    ),
                ),
            ],
        ),
    ]
