# Generated by Django 5.1.6 on 2025-09-30 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ModelParams",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("w_cpa", models.FloatField(default=0.25)),
                ("w_tcpa", models.FloatField(default=0.25)),
                ("w_tdb", models.FloatField(default=0.25)),
                ("w_twrp", models.FloatField(default=0.25)),
                ("cpa_scale_km", models.FloatField(default=20.0)),
                ("tcpa_scale_s", models.FloatField(default=120.0)),
                ("tdb_scale_km", models.FloatField(default=30.0)),
                ("twrp_scale_s", models.FloatField(default=120.0)),
                ("clamp_0_1", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Scenario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=128, unique=True)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, default="")),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrackSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("t", models.DateTimeField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("alt_m", models.FloatField()),
                ("speed_mps", models.FloatField()),
                ("heading_deg", models.FloatField()),
            ],
            options={
                "ordering": ["t"],
            },
        ),
        migrations.RenameField(
            model_name="track",
            old_name="timestamp",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="defendedasset",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="defendedasset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="threatscore",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threatscore",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="track",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="threatscore",
            name="da",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_scores",
                to="tewa.defendedasset",
            ),
        ),
        migrations.AlterField(
            model_name="threatscore",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_scores",
                to="tewa.track",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_id",
            field=models.CharField(max_length=64),
        ),
        migrations.AddIndex(
            model_name="defendedasset",
            index=models.Index(fields=["name"], name="tewa_defend_name_4f83f9_idx"),
        ),
        migrations.AddConstraint(
            model_name="defendedasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("radius_km__gte", 0)), name="da_radius_nonneg"
            ),
        ),
        migrations.AddIndex(
            model_name="scenario",
            index=models.Index(fields=["name"], name="tewa_scenar_name_039e16_idx"),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="scenario",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="params",
                to="tewa.scenario",
            ),
        ),
        migrations.AddField(
            model_name="threatscore",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_scores",
                to="tewa.scenario",
            ),
        ),
        migrations.AddField(
            model_name="track",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="tewa.scenario",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="threatscore",
            unique_together={("scenario", "track", "da", "computed_at")},
        ),
        migrations.AlterUniqueTogether(
            name="track",
            unique_together={("scenario", "track_id")},
        ),
        migrations.AddIndex(
            model_name="threatscore",
            index=models.Index(
                fields=["scenario", "da", "computed_at"],
                name="tewa_threat_scenari_0cc5ee_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="threatscore",
            index=models.Index(
                fields=["scenario", "track", "computed_at"],
                name="tewa_threat_scenari_0277ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["scenario", "track_id"], name="tewa_track_scenari_a864d0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["lat", "lon"], name="tewa_track_lat_d8954a_idx"),
        ),
        migrations.AddField(
            model_name="tracksample",
            name="track",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="samples",
                to="tewa.track",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("w_cpa__gte", 0), ("w_cpa__lte", 1)),
                name="w_cpa_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("w_tcpa__gte", 0), ("w_tcpa__lte", 1)),
                name="w_tcpa_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("w_tdb__gte", 0), ("w_tdb__lte", 1)),
                name="w_tdb_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("w_twrp__gte", 0), ("w_twrp__lte", 1)),
                name="w_twrp_0_1",
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("cpa_scale_km__gt", 0)), name="cpa_scale_gt0"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("tcpa_scale_s__gt", 0)), name="tcpa_scale_gt0"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("tdb_scale_km__gt", 0)), name="tdb_scale_gt0"
            ),
        ),
        migrations.AddConstraint(
            model_name="modelparams",
            constraint=models.CheckConstraint(
                condition=models.Q(("twrp_scale_s__gt", 0)), name="twrp_scale_gt0"
            ),
        ),
        migrations.AddIndex(
            model_name="tracksample",
            index=models.Index(
                fields=["track", "t"], name="tewa_tracks_track_i_3fa523_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="tracksample",
            index=models.Index(
                fields=["lat", "lon"], name="tewa_tracks_lat_2fbc59_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tracksample",
            unique_together={("track", "t")},
        ),
    ]
