# Generated by Django 5.1.6 on 2025-09-30 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0002_modelparams_scenario_tracksample_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelparams",
            options={
                "verbose_name": "Model params",
                "verbose_name_plural": "Model params",
            },
        ),
    ]
