# Generated by Django 5.1.6 on 2025-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0003_alter_modelparams_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scenario",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="scenario",
            name="tewa_scenar_name_039e16_idx",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="end_time",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="scenario",
            name="start_time",
        ),
        migrations.AddField(
            model_name="scenario",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
