# Generated by Django 5.1.6 on 2025-10-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0004_alter_scenario_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="scenario",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scenario",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
