# Generated by Django 5.1.6 on 2025-10-04 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0005_scenario_end_time_scenario_notes_scenario_start_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="modelparams",
            options={},
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="w_cpa_0_1",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="w_tcpa_0_1",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="w_tdb_0_1",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="w_twrp_0_1",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="cpa_scale_gt0",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="tcpa_scale_gt0",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="tdb_scale_gt0",
        ),
        migrations.RemoveConstraint(
            model_name="modelparams",
            name="twrp_scale_gt0",
        ),
        migrations.RemoveField(
            model_name="modelparams",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="modelparams",
            name="updated_at",
        ),
    ]
