# Generated by Django 5.1.6 on 2025-10-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0006_alter_modelparams_options_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="defendedasset",
            name="da_radius_nonneg",
        ),
        migrations.RemoveIndex(
            model_name="defendedasset",
            name="tewa_defend_name_4f83f9_idx",
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="radius_km",
            field=models.FloatField(),
        ),
    ]
