# Generated by Django 5.1.6 on 2025-10-07 04:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0007_remove_defendedasset_da_radius_nonneg_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="modelparams",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
