# Generated by Django 5.1.6 on 2025-10-10 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0008_modelparams_created_at_modelparams_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defendedasset",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
