# Generated by Django 5.1.6 on 2025-10-10 10:39

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0009_alter_defendedasset_id_alter_scenario_id"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="threatscore",
            name="tewa_threat_scenari_0cc5ee_idx",
        ),
        migrations.RemoveIndex(
            model_name="threatscore",
            name="tewa_threat_scenari_0277ed_idx",
        ),
        migrations.RenameIndex(
            model_name="track",
            new_name="idx_track_scn_id",
            old_name="tewa_track_scenari_a864d0_idx",
        ),
        migrations.RenameIndex(
            model_name="track",
            new_name="idx_track_lat_lon",
            old_name="tewa_track_lat_d8954a_idx",
        ),
        migrations.RenameIndex(
            model_name="tracksample",
            new_name="idx_sample_track_t",
            old_name="tewa_tracks_track_i_3fa523_idx",
        ),
        migrations.RenameIndex(
            model_name="tracksample",
            new_name="idx_sample_lat_lon",
            old_name="tewa_tracks_lat_2fbc59_idx",
        ),
        migrations.AlterUniqueTogether(
            name="threatscore",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="defendedasset",
            name="scenario",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defended_assets",
                to="tewa.scenario",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="threatscore",
            name="batch_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="lat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="lon",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="defendedasset",
            name="radius_km",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.001),
                    django.core.validators.MaxValueValidator(1000.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="end_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="scenario",
            name="start_time",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="threatscore",
            name="computed_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="threatscore",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="threatscore",
            name="scenario",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="threat_scores",
                to="tewa.scenario",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="track",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="track",
            name="heading_deg",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(360.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="lat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="lon",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="scenario",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to="tewa.scenario",
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="speed_mps",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="track",
            name="track_id",
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="heading_deg",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(360.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="lat",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-90.0),
                    django.core.validators.MaxValueValidator(90.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="lon",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(-180.0),
                    django.core.validators.MaxValueValidator(180.0),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="speed_mps",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="tracksample",
            name="t",
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterUniqueTogether(
            name="defendedasset",
            unique_together={("scenario", "name")},
        ),
        migrations.AddIndex(
            model_name="defendedasset",
            index=models.Index(fields=["scenario", "name"], name="idx_da_scn_name"),
        ),
        migrations.AddIndex(
            model_name="defendedasset",
            index=models.Index(fields=["lat", "lon"], name="idx_da_lat_lon"),
        ),
        migrations.AddIndex(
            model_name="threatscore",
            index=models.Index(
                fields=["scenario", "da", "-computed_at"], name="idx_ts_scn_da_cmp"
            ),
        ),
        migrations.AddIndex(
            model_name="threatscore",
            index=models.Index(
                fields=["scenario", "track", "-computed_at"], name="idx_ts_scn_trk_cmp"
            ),
        ),
        migrations.AddIndex(
            model_name="threatscore",
            index=models.Index(fields=["batch_id"], name="idx_ts_batch"),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(fields=["scenario"], name="idx_track_scn"),
        ),
    ]
