# Generated by Django 5.1.6 on 2025-10-13 06:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0010_da_scenario_nullable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="defendedasset",
            name="scenario",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="defended_assets",
                to="tewa.scenario",
            ),
        ),
    ]
