# Generated by Django 5.1.6 on 2025-10-15 10:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tewa", "0011_alter_defendedasset_scenario"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="modelparams",
            name="R_DA_m",
            field=models.PositiveIntegerField(default=8000, help_text="DA radius (m)"),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="R_W_m",
            field=models.PositiveIntegerField(
                default=25000, help_text="Weapon range (m)"
            ),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="sigma_cpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="sigma_tcpa",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="sigma_tdb",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="sigma_twrp",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="tick_s",
            field=models.FloatField(
                default=1.0,
                help_text="Tick rate (s)",
                validators=[django.core.validators.MinValueValidator(1e-06)],
            ),
        ),
        migrations.AddField(
            model_name="modelparams",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_params",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="w_cpa",
            field=models.FloatField(
                default=0.35,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="w_tcpa",
            field=models.FloatField(
                default=0.25,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="w_tdb",
            field=models.FloatField(
                default=0.2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="modelparams",
            name="w_twrp",
            field=models.FloatField(
                default=0.2,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
    ]
