# .github/workflows/ci.yml
name: Django CI
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: missile_model
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s
          --health-timeout=5s --health-retries=5
    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/missile_model
      DJANGO_SETTINGS_MODULE: missile_model.settings
      PYTHONUNBUFFERED: "1"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt
      - run: python manage.py migrate --noinput
      - run: coverage run -m pytest -q
      - run: coverage report --fail-under=85
